version: '3'

services:

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./backend:/var/www
        ports:
            - 80:80
            - 8080:8080
        depends_on:
            - php
            - npmvue
        links:
            - php
            - npmvue
        networks:
            - docker-network

    php:
        container_name: php8-fpm
        restart: always
        image: php8-fpm
        build:
            dockerfile: php8-fpm.dockerfile
            context: ./docker/php
        expose:
            - "9000"
        volumes:
            - ./backend:/var/www/
        environment:
            - "DB_HOST=mysql"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        depends_on:
            - mysql
        links:
            - mysql
        networks:
            - docker-network

    npmvue:
        container_name: vue
        image: npmvue
        build: ./docker/npm
        restart: unless-stopped
        volumes:
            - ./frontend:/var/www
        networks:
            - docker-network
        depends_on:
            - php

    mysql:
        image: mysql:8
        container_name: mysql8
        restart: always
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
