version: '3'

services:
    vueapp:
        image: node:latest
        container_name: vueapp
        volumes:
            - ./frontend:/
        ports:
            - 80:8000
        networks:
            - docker-network
        depends_on:
            - php
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        ports:
            - 8080:80
        depends_on:
            - php
        links:
            - php
        networks:
            - docker-network

    php:
        container_name: php8-fpm
        restart: always
        image: php8-fpm
        build:
            dockerfile: php8-fpm.dockerfile
            context: ./docker/php
        expose:
            - "9000"
        volumes:
            - ./backend:/var/www/
        environment:
            - "DB_HOST=mysql"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        depends_on:
            - mysql
        links:
            - mysql
        networks:
            - docker-network

    mysql:
        image: mysql:8
        container_name: mysql8
        restart: always
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
